### ISSUE TITLE
Invalid URL prefix in "/oauth/token"

### ISSUE THREAD

**Issue by srinat999** [icclab/cf-webui#15]
Hi, 

I managed to get push this UI, but on loggin in I am getting this error:

```
 ERR 2016/09/14 15:08:52 [error] 37#0: *14 invalid URL prefix in "/oauth/token", client: 10.0.0.130, server: , request: "POST /oauth HTTP/1.1", host: "ui.apps.de.cloudfoundry.it-platforms.net", referrer: "https://ui.apps.de.cloudfoundry.it-platforms.net/"
```

It seems the app is making the authenticate request to itself rather than to the CF API endpoint. Any idea how to fix this?

Here is my manifest.yml

```

---
applications:
- name: cf-webui
  memory: 128M
  host: ui
  path: ./build
  buildpack: staticfile_buildpack
  env:
    API_ENDPOINT: http://api.sys.de.cloudfoundry.it-platforms.net
    # Use Google DNS by default
    NGINX_RESOLVER: 10.0.0.114
    #Enforce https is used (using x_forwarded_proto check) .Default: enabled
    FORCE_HTTPS: 0
    http_proxy: "http://10.10.0.1:3128"
    https_proxy: "http://10.10.0.1:3128"
    no_proxy: "api.sys.de.cloudfoundry.it-platforms.net,10.0.0.125,10.0.0.130"
```

As you can see, I'm also under a proxy
